// <auto-generated />
using System;
using Chat.Dal.EfStructres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chat.Dal.EfStructres.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241024212901_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatModels.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("Post_pkey");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("ChatModels.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<char?>("Name")
                        .HasColumnType("char")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("User_pkey");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ChatModels.Entities.Post", b =>
                {
                    b.HasOne("ChatModels.Entities.User", "IdNavigation")
                        .WithOne("Post")
                        .HasForeignKey("ChatModels.Entities.Post", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("id");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("ChatModels.Entities.User", b =>
                {
                    b.Navigation("Post");
                });
#pragma warning restore 612, 618
        }
    }
}
